openapi: 3.0.0
info:
  title: Car Parking API
  version: 1.0.0
servers:
  - url: https://car-parking-api.test
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /api/v1/auth/register:
    post:
      tags:
        - default
      summary: auth/register
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of user
                  example: John Doe
                email:
                  type: string
                  description: Email address (must be unique in database)
                  example: john.doe@domain.com
                password:
                  type: string
                  description: Password
                  example: password
                password_confirmation:
                  type: string
                  description: Password confirmation (must match password above)
                  example: password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - default
      summary: auth/login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email address
                  example: gkimpson@gmail.com
                password:
                  type: string
                  description: Password
                  example: password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/logout:
    post:
      tags:
        - default
      summary: auth/logout
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/parkings/start:
    post:
      tags:
        - default
      summary: parkings/start
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                vehicle_id:
                  type: integer
                  description: Vehicle id (primary key in database table)
                  example: '1'
                zone_id:
                  type: integer
                  description: Zone id (primary key in database table)
                  example: '2'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/parkings/1:
    get:
      tags:
        - default
      summary: parkings/show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: parkings/stop
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reg_number:
                  type: string
                  description: Vehicle registration number (min 5 chars)
                  example: AAA123
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vehicles:
    get:
      tags:
        - default
      summary: vehicles/index
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: vehicles/store
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reg_number:
                  type: string
                  description: Vehicle registration number (min 5 chars)
                  example: AAA123
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/vehicles/1:
    get:
      tags:
        - default
      summary: vehicles/show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: vehicles/update
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                reg_number:
                  type: string
                  description: Vehicle registration number (min 5 chars)
                  example: GK10ABC
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: vehicles/delete
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/profile:
    get:
      tags:
        - default
      summary: profile/show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: profile/update
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Name of user
                  example: Gavin Kimpson
                email:
                  type: string
                  description: Email address
                  example: gkimpson@gmail.com
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/password:
    put:
      tags:
        - default
      summary: password/update
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: Current password
                  example: password12
                password:
                  type: string
                  description: New password
                  example: password
                password_confirmation:
                  type: string
                  description: New password confirmation (must must password above)
                  example: password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/zones:
    get:
      tags:
        - default
      summary: zones/index
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/zones/1:
    get:
      tags:
        - default
      summary: zones/show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
