version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx 
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      -  car_parking_network

  app:
    image: carparkingapp-image
    container_name: carparkingapp-api
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - user=dev
        - uid=1000
    working_dir: /var/www/html
    restart: always
    volumes:
      - ./src:/var/www/html/src:rw
      - ./public:/var/www/html/public:rw
    depends_on:
      - db
    networks:
      -  car_parking_network
    
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    user: mysql
    environment:
      - MYSQL_DATABASE=car_parking_api
      - MYSQL_USER=dev
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=dev

    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql:rw
      - ./docker/mysql/conf.d:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
      - car_parking_network


networks:
  car_parking_network:
    driver: bridge